### ISSUE TITLE
Refactor :: 비효율적인 디비 구조 개선

### ISSUE THREAD

**Issue by yeseong0412** [apeun-gidaechi/seugi-server#133]
## 📎 고쳐야 할 것
1. 현재 디비 구조가 너무 비효율적이다
- 채팅방 하나를 검색할때 MongoDB 와 MySQL 두가지에 모두 접근
2. 해결해야할것
- 채팅방과 워크스페이스 모두 MySQL로 구성
- 메시지만 MongoDB 사용

### 🥰 기타
긴 싸움이 되겠네요....ㅎ

**Comment by hw0k** [comment]
이 이슈 이번 시간에 같이 볼까요?

**Comment by yeseong0412** [comment]
> 이 이슈 이번 시간에 같이 볼까요?

넵

근데 다시금 디비 구조를 생각하니 수많은 연관관계가 발생할 것 같아서 차라리 MongoDB를 사용하여 Workspace, ChatRoom을 연결해야하나 도 생각중에 있어요

**Comment by yeseong0412** [comment]
그냥 Workspace도 기존에 몽고에 있고 ChatRoom만 몽고로 이전하면 되는상황이라 ChatRoom만 몽고로 이전하겠습니다

**Comment by seu1a** [comment]
이슈 닫겠습니다 #135
