### ISSUE TITLE
급식 불러오기

### ISSUE THREAD

**Issue by yeseong0412** [apeun-gidaechi/seugi-server#188]
# 🔥할 일
- [x] 급식 불러오기 로직 개발

## 📎 ETC 
- 병춘춘병춘 서버를 이용할지 나이스를 이용할지 고민해봐야함

**Comment by 8954sood** [comment]
1. 병춘춘병춘 서버는 가끔 오라클의 자원 압수로 꺼지므로 나이스 서버를 이용하는 것을 권장합니다.
2. 나이스 서버를 이용할 경우 내용에 존재하는 html을 파싱하여야 합니다.
3. 해당 데이터는 캐싱을 권장하지만, 가끔 학교마다 그 주에 급식을 결정해서 다음주 급식을 흰쌀밥 만 넣어뒀다가 그주에 새로 반영하는 경우가 있습니다.
4. 나이스 서버는 일일 최대 1000회 조회가 가능합니다.

**Comment by yeseong0412** [comment]
> 1. 병춘춘병춘 서버는 가끔 오라클의 자원 압수로 꺼지므로 나이스 서버를 이용하는 것을 권장합니다.
> 2. 나이스 서버를 이용할 경우 내용에 존재하는 html을 파싱하여야 합니다.
> 3. 해당 데이터는 캐싱을 권장하지만, 가끔 학교마다 그 주에 급식을 결정해서 다음주 급식을 흰쌀밥 만 넣어뒀다가 그주에 새로 반영하는 경우가 있습니다.
> 4. 나이스 서버는 일일 최대 1000회 조회가 가능합니다.

생각을 해봤는데 학교별 조회를 해야해서 나이스 사용을 해야할 것 같아요
