### ISSUE TITLE
Auth 완성

### ISSUE THREAD

**Issue by seu1a** [apeun-gidaechi/seugi-server#2]
🐳 할 일
- [x] JWT 구현
- [x] 구글 OAuth2 구현
- [ ] 애플 OAuth2 구현

**Comment by yeseong0412** [comment]
구글 Auth랑 Apple auth 개발 다 됬나요?

**Comment by yeseong0412** [comment]
이슈를 새로 만들었군요 확인했습니다~

**Comment by seu1a** [comment]
이슈 세분화 했습니다 😀

**Comment by yeseong0412** [comment]
#50 #232
