### ISSUE TITLE
유저 조회 시 존재하지 않을 경우 null 발생

### ISSUE THREAD

**Issue by seu1a** [apeun-gidaechi/seugi-server#23]
# 🤮 버그
- [x] JPA의 쿼리문을 QueryDSL로 바꾼 후 유저 조회 시 유저가 없을 경우의 익셉션에서 null이 발생

## 📎 고쳐야 할 것
- [x] CustomException 관련 null 위험 제거

### 🥰 기타
- 화이팅 👏👏👏👏

**Comment by yeseong0412** [comment]
@seu1a 이거 수정 다한건가요?

**Comment by seu1a** [comment]
네네 닫겠습니다 😃
